DepartsCrud/Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace DepartsCrud.Models;

public class Employee
{
    public Employee()
    {
    }

    public Employee(int id, string name, string position, double salary, int departmentId)
    {
        Id = id;
        Name = name;
        Position = position;
        Salary = salary;
        DepartmentId = departmentId;
    }

    [HiddenInput] public int Id { get; set; }

    [Required] public string? Name { get; set; }

    [Required] public string? Position { get; set; }

    public double? Salary { get; set; }

    [Display(Name = "Department")]
    [Range(1, int.MaxValue, ErrorMessage = "Department is required")]
    public int DepartmentId { get; set; }

    public Department? Department { get; set; }
}

DepartsCrud/ViewModels/EmployeeViewModel.cs
using DepartsCrud.Models;

namespace DepartsCrud.ViewModels;

public class EmployeeViewModel
{
    public Employee? Employee { get; set; }
    public List<Department>? Departments { get; set; }
}

DepartsCrud/Pages/Employees/Create.cshtml.cs
using DepartsCrud.Helpers;
using DepartsCrud.Models;
using DepartsCrud.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DepartsCrud.Pages.Employees;

public class Create : PageModel
{
    private readonly IDepartmentsRepository _departmentsRepository;
    private readonly IEmployeesRepository _employeesRepository;

    public Create(IDepartmentsRepository departmentsRepository, IEmployeesRepository employeesRepository)
    {
        _departmentsRepository = departmentsRepository;
        _employeesRepository = employeesRepository;
    }
    [BindProperty] public EmployeeViewModel? EmployeeViewModel { get; set; }

    public void OnGet()
    {
        this.EmployeeViewModel = new EmployeeViewModel();
        this.EmployeeViewModel.Employee = new Employee();
        this.EmployeeViewModel.Departments = _departmentsRepository.GetDepartments();
    }

    public IActionResult OnPost()
    {
        if (!ModelState.IsValid)
        {
            var errors = ModelStateHelper.GetErrors(ModelState);
            return RedirectToPage("/Error", new { errors });
        }

        if (this.EmployeeViewModel is not null && this.EmployeeViewModel.Employee is not null)
        {
            _employeesRepository.AddEmployee(this.EmployeeViewModel.Employee);
        }

        return RedirectToPage("Index");
    }
}

DepartsCrud/Pages/Employees/DepartmentEmployees.cshtml.cs
using DepartsCrud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DepartsCrud.Pages.Employees;

public class DepartmentEmployees : PageModel
{
    private readonly IDepartmentsRepository _departmentsRepository;

    public DepartmentEmployees(IDepartmentsRepository departmentsRepository)
    {
        _departmentsRepository = departmentsRepository;
    }
    public string? DepartmentName { get; set; }
    [BindProperty(SupportsGet = true)]
    public int? DepartmentId { get; set; }
    
    public void OnGet(int? departmentId)
    {
        if (departmentId.HasValue)
        {
            var department = _departmentsRepository.GetDepartmentById(DepartmentId.Value);
            DepartmentName = department?.Name;
        }
    }
}

DepartsCrud/Pages/Employees/Edit.cshtml.cs
using DepartsCrud.Helpers;
using DepartsCrud.Models;
using DepartsCrud.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DepartsCrud.Pages.Employees;

public class Edit : PageModel
{
    private readonly IEmployeesRepository _employeesRepository;
    private readonly IDepartmentsRepository _departmentsRepository;

    public Edit(IEmployeesRepository employeesRepository, IDepartmentsRepository departmentsRepository)
    {
        _employeesRepository = employeesRepository;
        _departmentsRepository = departmentsRepository;
    }
    
    [BindProperty]
    public EmployeeViewModel? EmployeeViewModel { get; set; }
    public void OnGet(int id)
    {
        this.EmployeeViewModel = new EmployeeViewModel();
        this.EmployeeViewModel.Employee = _employeesRepository.GetEmployeeById(id);
        this.EmployeeViewModel.Departments = _departmentsRepository.GetDepartments();
        
    }   
    
    public IActionResult OnPost()
    {
        if (!ModelState.IsValid)
        {
            var errors = ModelStateHelper.GetErrors(ModelState);
            return RedirectToPage("/Error", new { errors });
        }

        if (EmployeeViewModel is not null && EmployeeViewModel.Employee is not null)
        {
            _employeesRepository.UpdateEmployee(EmployeeViewModel.Employee);
        }

        return RedirectToPage("Index");
    }
    
    public IActionResult OnPostDeleteEmployee(int id)
    {
        var employee = _employeesRepository.GetEmployeeById(id);
        if (employee == null)
        {
            ModelState.AddModelError("id", "Employee not found");
            var errors = ModelStateHelper.GetErrors(ModelState);
            return RedirectToPage("/Error", new { errors });
        }
        
        _employeesRepository.DeleteEmployee(employee);
        return RedirectToPage("Index");
    }
}

DepartsCrud/Pages/Employees/Index.cshtml.cs
using DepartsCrud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DepartsCrud.Pages.Employees;

public class Index : PageModel
{
    public List<Employee>? Employees { get; set; }

    public void OnGet()
    {
        // this.Employees = EmployeesRepository.GetEmployees();
    }

    public IActionResult OnGetSearchEmployeeResult(string? filter)
    {
        return ViewComponent("EmployeeList", new { filter });
    }
}

DepartsCrud/Pages/Shared/Components/EmployeeList/EmployeeListViewComponent.cs
using DepartsCrud.Models;
using Microsoft.AspNetCore.Mvc;

namespace DepartsCrud.Pages.Shared.Components.EmployeeList;

public class EmployeeListViewComponent: ViewComponent
{
    private readonly IEmployeesRepository _employeesRepository;

    public EmployeeListViewComponent(IEmployeesRepository employeesRepository)
    {
        _employeesRepository = employeesRepository;
    }
    public IViewComponentResult Invoke(string? filter, int? departmentId )
    {
        return View(_employeesRepository.GetEmployees(filter, departmentId));
    }
}

DepartsCrud/Pages/Employees/Create.cshtml
@page "/create-employees"
@model DepartsCrud.Pages.Employees.Create

@{
    ViewBag.Action = "create";
}
@section title_section
{
    <h3>Add Employee</h3>
}

@* @await Html.PartialAsync("_EmployeeDetail", Model.EmployeeViewModel) *@
<partial name="_EmployeeDetail" model="@Model.EmployeeViewModel" />

DepartsCrud/Pages/Employees/DepartmentEmployees.cshtml
@page "{departmentId:int}"
@model DepartsCrud.Pages.Employees.DepartmentEmployees

@section title_section
{
    <h3>Employees of Departmetn: @Model.DepartmentName</h3>
}
<table class="table table-striped">
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Position
        </th>
        <th>Salary</th>
        <th>Department</th>
        <th></th>
    </tr>
    </thead>
    <tbody id="employee-list">
    @* @await Component.InvokeAsync("EmployeeList", new {filter = "", departmentId = Model.DepartmentId})  *@
    <vc:employee-list filter="" department-id="@Model.DepartmentId"></vc:employee-list>
    </tbody>
</table>

DepartsCrud/Pages/Employees/Edit.cshtml
@page "{id:int}"
@model DepartsCrud.Pages.Employees.Edit
@{
    ViewBag.Action = "edit";
}

@section title_section
{
    <h3>Edit Employee</h3>
}

@* @await Html.PartialAsync("_EmployeeDetail", Model.EmployeeViewModel) *@
<partial name="_EmployeeDetail" model="@Model.EmployeeViewModel" />

<form name="deleteEmployeeForm" method="post"
      asp-page="/employees/edit"
      asp-route-id="@Model.EmployeeViewModel.Employee.Id"
      asp-page-handler="DeleteEmployee"
      >
    <button type="submit" id="delete-employee" class="btn btn-danger">Delete</button>
</form>

@section scripts
{
    <script>
        document.querySelector('#delete-employee').addEventListener('click', (e) => {
            e.preventDefault();
            const employeeName = '@Model.EmployeeViewModel.Employee.Name';
            const userConfirmation =  confirm(`Are you sure you want to delete the employee: ${employeeName}`);
            if (userConfirmation) {
                document.forms["deleteEmployeeForm"].submit();
            }
        })
    </script>
}

DepartsCrud/Pages/Employees/Index.cshtml
@page
@model DepartsCrud.Pages.Employees.Index


@section title_section
{

    <h3>Employees</h3>
}


@{
    Layout = "_Layout";
    ViewBag.Title = "Departments";
}


@* @await Html.PartialAsync("_SearchBar") *@
<partial name="_SearchBar" />
<table class="table table-striped">
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Position
        </th>
        <th>Salary</th>
        <th>Department</th>
        <th></th>
    </tr>
    </thead>
    <tbody id="employee-list">

    </tbody>
</table>

<br/>
<a asp-page="/employees/create" class="btn btn-primary">Add</a>

@section scripts{
    <script>
        loadEmployees('');

        document.querySelector("#search-button").addEventListener("click", async (e) => {
            var filter = document.querySelector("#search-filter").value.trim();
            await loadEmployees(filter);
        });

        async function loadEmployees(filter) {
            var response = await fetch(`/employees?filter=${filter}&handler=SearchEmployeeResult`);
            var html = await response.text();
            document.querySelector("#employee-list").innerHTML = html;
        }
    </script>

}

DepartsCrud/Pages/Employees/_EmployeeDetail.cshtml
@model EmployeeViewModel

@if (Model is not null && Model.Employee is not null)
{
    <form method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        @if (ViewBag.Action == "edit")
        {
            <input asp-for="Employee.Id"/>
        }
        <div class="row mb-3">
            <div class="col-2">
                <label class="col-form-label" asp-for="Employee.Name"></label>
            </div>
            <div class="col-6">
                <input class="form-control" asp-for="Employee.Name"/>
                <span class="text-danger" asp-validation-for="Employee.Name"></span>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-2">
                <label class="col-form-label" asp-for="Employee.Position"></label>
            </div>
            <div class="col-6">
                <input class="form-control" asp-for="Employee.Position"/>
                <span class="text-danger" asp-validation-for="Employee.Position"></span>
                
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-2">
                <label class="col-form-label" asp-for="Employee.Salary"></label>
            </div>
            <div class="col-6">
                <input class="form-control" asp-for="Employee.Salary"/>
                <span class="text-danger" asp-validation-for="Employee.Salary"></span>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-2">
                <label class="col-form-label" asp-for="Employee.DepartmentId"></label>
            </div>
            <div class="col-6">
                <select
                    asp-for="Employee.DepartmentId"
                    asp-items='Model.Departments.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString(), Selected = (ViewBag.Action == "edit" && x.Id == Model.Employee.DepartmentId) })'
                    class="form-control">
                    <span class="text-danger" asp-validation-for="Employee.DepartmentId"></span>
                    if (ViewBag.Action == "create")
                    {
                    <option selected="selected" value="0">--- Please Select ---</option>
                    }
                </select>
                <span class="text-danger" asp-validation-for="Employee.DepartmentId"></span>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-2">
                <button type="submit" class="btn btn-primary">Save</button>
                <a asp-page="/employees/index" class="btn btn-secondary">Cancel</a>
            </div>
            <div class="col-4">
            </div>
        </div>

    </form>
}

DepartsCrud/Pages/Employees/_EmployeeListItem.cshtml
@model Employee
@if (Model is not null)
{
    <tr>
        <td>@Model.Name</td>
        <td>@Model.Position</td>
        <td>@Model.Salary</td>
        <td><a class="btn btn-link"
               asp-controller="Departments"
               asp-route-id="@Model.DepartmentId"
            >@Model.Department?.Name</a>
        </td>
        <td><a class="btn btn-link"
               asp-page="/employees/edit"
               asp-route-id="@Model.Id">Edit</a></td>
    </tr>
}